name: Deploy Pointato

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd /home/hyeonjh/pointato
          git fetch origin main
          git reset --hard origin/main

      - name: Install dependencies
        run: |
          cd /home/hyeonjh/pointato/backend
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restart pointato
        run: |
          sudo systemctl restart pointato